### PR TITLE
Added Some More Hindi translation Reviews.

### PR DESCRIPTION
**Pull request by sshiv5768**
Just added some more Hindi translation reviews of AFL and Atom keywords. 
Tasks :
1: Review each translations
2: Checked if any better translation available
3: Added better translations with ❓ into the comments
4: If translation is perfect then added ✅ into the comments.

### CODE REVIEW

**Review by madiedgar — CHANGES_REQUESTED** [review]
@sshiv5768 thanks for you patience, as I was a little confused as to what's going on. 

I looked at the most recent translation commits that you've made on your branch and they look great. 👍 
- `e15e5c718cb874e081f5cb354ec5d56f4db0d326`
- `c961e3bcecfe966023b06c1bb79c1877dff0fa28`
- `98cef23c95bd17a2bd72e973c0df9d5d424299f4`

However, it seems that you did not `git pull` the latest changes before you made updates.  So you're missing several commits and working off an outdated branch. 

There is a way to get your branches back on track, but it might take a lot of work. I suggest you start clean with a fresh fork from `legesher/legesher-translations` (this will most likely require you to delete or rename your current fork). Make the same changes you did from the commits listed above ^ on the new fork's `hindi-translation` branch. Then submit a new PR. 

I'm going to close this PR, as I'll be looking out for a new one with the changes. Let me know if you have any questions. 👍

**Comment by sshiv5768** [comment]
So i should first do fetch and upstream this hindi translations branch, than i should pull the changes and do that reviews again right? @madiedgar ?

**Comment by madiedgar** [comment]
Hey @sshiv5768, yes if that's possible.

**Comment by sshiv5768** [comment]
Great, now got the whole scenario, thanks @madiedgar. I will do that.

**Pull request closed without merging**
