### PR TITLE
Add a french .yml file and start python translation

### LINKED ISSUE #17: Add new Dialect: French(Python)
Hello @madiedgar, I would like to contribute with french translation if needed.

### PR DESCRIPTION
**Pull request by wang-ories**
fix #17

### CODE REVIEW

**Comment by madiedgar** [comment]
Hey @wang-ories 👋! Thanks for getting a head start on this!  I merged my translation changes into the master branch that has the `locale/` folder with the base `.yml` file to use. If you could use that file as a base and translate as much as you can of the python programming language, I'll be more than happy to accept your PR! 👍

**Comment by wang-ories** [comment]
> Hey @wang-ories 👋! Thanks for getting a head start on this! I merged my translation changes into the master branch that has the `locale/` folder with the base `.yml` file to use. If you could use that file as a base and translate as much as you can of the python programming language, I'll be more than happy to accept your PR! 👍

Hi @madiedgar, 
Is language-keyword-template.yml the base file?

**Comment by madiedgar** [comment]
@wang-ories Yes 👍 `language-keyword-template.yml` is the base file.

**Comment by wang-ories** [comment]
> @wang-ories Yes 👍 `language-keyword-template.yml` is the base file.

Thank You!

**Comment by madiedgar** [comment]
I'm going to close this one as you rocked it with the other PR 👍 🎉

**Pull request closed without merging**
