### PR TITLE
Portuguese translation @katherinefernandes

### LINKED ISSUE #9: Add New Dialect: Portuguese (Python)
## Adding Portuguese to the Legesher Translations for Python
Version 1 of Legesher only includes translations for the Python programming language. In order to add this language to the project, complete the steps detailed in [the translation guide](https://legesher.readme.io/docs/translation-guide)

### Reviewers Needed
In order to add the translations into our database to use, the translations will need to be approved and accepted by 3 additional native / fluent speakers. If you would like to be one of the reviewers for this language, please mention in this issue! :smile:

### PR DESCRIPTION
**Pull request by katherinefernandes**
I started to translate and I just want to make sure if, by doing this, you are able to accept it or not :)

Fix #9

### CODE REVIEW

**Comment by madiedgar** [comment]
I need to fix the configurations on the linting, so don't worry about the checks failing. Could you add Davi's translations for python?  Then we can merge this PR 🎉

**Comment by katherinefernandes** [comment]
Yes, I can! I am just wondering if I have to add just one word for each or the list of words that he came with!

**Comment by madiedgar** [comment]
Good question @katherinefernandes 😄 Could you pick the one that you believe would be the best fit and enter that within the `""` and then comment out the rest of the commentary? Something like this:

```yml
await: "aguardar" # esperar - look forward to the probable occurrence of
```

**Comment by katherinefernandes** [comment]
Yes, I will centainly do that and it will be done by tomorrow, I think I can also add more :) @madiedgar

**Comment by madiedgar** [comment]
Hey @katherinefernandes! Any updates on this? I want to make sure you get your credit for the hard work you put in! 😄

**Comment by madiedgar** [comment]
Congrats on merging your first pull request @katherinefernandes! 🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

**Comment by katherinefernandes** [comment]
Hey! I am so sorry I haven't had time to work on it! I will of course try to translate more soon :)

**Comment by madiedgar** [comment]
No worries!! I really appreciate all the work you've put in already 😄 and excited for what's to come!

**Pull request merged**
