### PR TITLE
review: Telugu translation

### PR DESCRIPTION
**Pull request by manojkrishnak**
## Title

Review Telugu translation for Python language

This pull request (PR) is made in reference to: #172 

## Description

Changed made to: 
- te.yml file

### CODE REVIEW

**Comment by manojkrishnak** [comment]
Hi @madiedgar, I have reviewed the Telugu language translation for Python programming. Please merge the pull request.

**Review by madiedgar — APPROVED** [review]
This is fantastic! 👍  Thank you @manojkrishnak

**Comment by madiedgar** [comment]
Thank you @manojkrishnak for your contribution! 👍 Really appreciate your help

**Comment by manojkrishnak** [comment]
Thank you @madiedgar for providing me an opportunity to contribute :)

**Comment by manojkrishnak** [comment]
Can you please give hactoberfest-accepted tag to this pull request.

**Pull request merged**
