### PR TITLE
Some hindi translations of the programming words

### PR DESCRIPTION
**Pull request by sshiv5768**
> Make sure you go through the [Contributing guide](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md).

> Please delete options that are not relevant.

## Title

This pull request (PR) is made in reference to: 

## Description

> What does this PR do?

> Recommendations for how to test this?

## Motivation and Context

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Testing

* [ ] My submission passes the tests?
  - If you did additional testing, please describe in detail how you tested your changes
* [ ] I added new tests for core changes, as applicable?

### CODE REVIEW

**Comment by madiedgar** [comment]
Hey @sshiv5768 👋🏾 Thanks so much for this contribution! Would love to incorporate this into our current Hindi branch `hindi-translation`. I linked issue #121 Review Dialect: Hindi (Python) which has a bit more information regarding how the translation review works. Let me know if you have any questions!

**Comment by madiedgar** [comment]
Thanks @sshiv5768 for updating this PR. Could you use the [`hindi-translation` branch](https://github.com/legesher/legesher-translations/tree/hindi-translation) as the branch to merge into instead of the master branch? When the translation is complete with all of the reviews it will be merged into master. 👍🏾 Then, you can compare what the initial translator added with your own comments. The key is described in issue #121. Let me know if you have any questions!

**Comment by sshiv5768** [comment]
Okay, @madiedgar. One more thing if you want to assign me other language's hindi translation then  I would love do it also.

**Comment by madiedgar** [comment]
Appreciate your enthusiasm @sshiv5768. If you know another language, I'll be more than happy to assign you to an open issue. Or if there's a language that's not currently in progress, we can add it.

**Comment by sshiv5768** [comment]
@madiedgar, 🤗

**Review by madiedgar — CHANGES_REQUESTED** [review]
I changed the base of your pull request to the `hindi-translation` branch which now is posing some merge conflicts. Take the current hi.yml file from this branch and incorporate your translations. Let me know if you have any questions!

**Comment by sshiv5768** [comment]
Thanks @madiedgar, If I have any questions I will definitely ask you.

**Comment by madiedgar** [comment]
Hey @sshiv5768 👋 Would love to incorporate your contributions, but some changes are needed before I can merge. Do you mind making the necessary changes (with the new base branch as `hindi-translation` instead of `master`)?

**Comment by sshiv5768** [comment]
I happy to work on it, just list me out the changes that are needed. I will complete it today.

**Comment by sshiv5768** [comment]
@madiedgar, I will complete all the required changes today. Just tell me the list of changes.

**Comment by madiedgar** [comment]
You're wonderful - It might be easier to start a new PR using the [`hindi-translation`](https://github.com/legesher/legesher-translations/tree/hindi-translation) branch, but since there has already been an initial translator for Hindi, you'll add to their contribution. The [translation guide](https://docs.legesher.io/legesher-translations/translation-guide) will prove to be most helpful, but if you have any specific questions, definitely reach out 👍

**Comment by sshiv5768** [comment]
Okay, just give me 2 days.

**Comment by sshiv5768** [comment]
Hey @madiedgar, Should I change my translations back to where the question mark is?

**Comment by madiedgar** [comment]
Going to close this one, since we're working on #148

**Pull request closed without merging**
