### PR TITLE
Review: Python, Finnish finished by minna-xd

### PR DESCRIPTION
**Pull request by minna-xD**
## Finnish review finished by minna-xd

This pull request (PR) is made in reference to: 
#170

## Python keywords

I've added my review comments to the existing Python keywords.

### CODE REVIEW

**Comment by minna-xD** [comment]
I need help with what I need to fix here. 😬

**Review by madiedgar — APPROVED** [review]
This is incredible and so thorough. Really appreciate your contribution!

**Comment by madiedgar** [comment]
There's a known problem with the beautifier that needs to be fixed, nothing to worry about here! 👍🏾👍🏾

**Comment by minna-xD** [comment]
Happy to help! Look forward to the other reviewer's comments. This was a refreshing "exercise".

**Pull request merged**
