### PR TITLE
Reviewed the German translation of Python

### PR DESCRIPTION
**Pull request by nausicaea**
Based on the original PR for German #12

### CODE REVIEW

**Comment by nausicaea** [comment]
Thanks for assigning the corresponding issue. In the meantime, I saw that another reviewer had reviewed German. Is there any way you would like us to coordinate? Also, how can I make the CI checks pass?

**Comment by madiedgar** [comment]
Congrats on merging your first pull request @nausicaea ! 🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

**Comment by nausicaea** [comment]
> Thank you @nausicaea for your thoroughness with the translations. Don't mind the CI checks (I need to fix something with the linter). I'm going to merge in your changes as you followed the structure correctly and then ask them to review off of the new version. Would love your insight when they all come together though!
> 
> Thank you! 😄

You're welcome! Please, feel free to ping me at any time if there's some additional help you need with the project (and of course, once the German review is complete)!

**Comment by nausicaea** [comment]
Oh shucks, I just noticed an error in my review. Line [`1371`](https://github.com/nausicaea/legesher-translations/blob/4c29b850c8a4a12cae860537398bad046cd950aa/de.yaml#L1371) should be translated to `menge` and not `setze`, because it refers to the mutable equivalent of `frozenset`.

**Comment by madiedgar** [comment]
No worries @nausicaea if you want to make another pull request, I'll be happy to accept the change 👍

**Pull request merged**
