### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by tomekp97**
Hey, here it is!
Left some comments by the Python section for the next person looking at this with some suggestions / questions. Do you have a way you'd prefer suggestions/question for others to be presented, like a separate read-me file?

### CODE REVIEW

**Comment by tomekp97** [comment]
Uh oh - computer really dislikes something in those files - do you know if this is something I need to fix up?

**Comment by madiedgar** [comment]
> Uh oh - computer really dislikes something in those files - do you know if this is something I need to fix up?

lol, yeah the linter goes crazy with these files. No worries though!

**Comment by madiedgar** [comment]
Congrats on merging your first pull request @tomekp97! 🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

**Comment by tomekp97** [comment]
Happy to help! Looking forward to future collaboration!

**Pull request merged**
