### PR TITLE
Create de.yaml, add german translation for python.

### PR DESCRIPTION
**Pull request by ZeroOne010101**
Some stuff needs a second opinion. Python is located at line 1247.

### CODE REVIEW

**Comment by ZeroOne010101** [comment]
Oh boy, there go the unittests.

**Comment by madiedgar** [comment]
I think it's throwing errors because of the branch 🤷‍♀, we'll make sure it's good to go before we merge it into master. It looks great though @ZeroOne010101 👍

**Comment by madiedgar** [comment]
Congrats on merging your first pull request @ZeroOne010101 ! 🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

**Comment by ZeroOne010101** [comment]
@madiedgar sorry, but i prefer not to let unknown people on the web know where i live. im looking forward to working with you too :smile:

**Pull request merged**
