### PR TITLE
feat: review language (Python) - Hebrew translation

### PR DESCRIPTION
**Pull request by michalirak**
## feat: review language (Python) - Hebrew translation

This pull request (PR) is made in reference to #171 

## Description

* Added translation for Atom keywords
* Added translation for python keywords and builtins

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Testing
Added translation and not code, so not relevant.

- [ ] My submission passes the tests?
- [ ] I added new tests for core changes, as applicable?

### CODE REVIEW

**Comment by michalirak** [comment]
Hi @madiedgar :)
Took a long time to get round to this, but I have finished the full python translation.
I couldn't understand the check fail, so I would appreciate some insight into what needs to be changed.
On another note, if I should add more translations in this PR or in a different one, I would be happy to do so.

**Comment by TomerPacific** [comment]
@michalirak , @madiedgar -[ this SO question](https://stackoverflow.com/questions/49297153/why-is-it-not-a-commit-and-a-branch-cannot-be-created-from-it) might help with the failure in Unibeautify.

**Review by madiedgar — APPROVED** [review]
This looks fantastic @michalirak! thank you so much for your thoroughness in this PR.

**Comment by madiedgar** [comment]
> @michalirak , @madiedgar -[ this SO question](https://stackoverflow.com/questions/49297153/why-is-it-not-a-commit-and-a-branch-cannot-be-created-from-it) might help with the failure in Unibeautify.

Thanks @TomerPacific, I'll look into this! For right now @michalirak, don't worry about the error.

**Pull request merged**
