### PR TITLE
Added Review on Indonesian Translation

### PR DESCRIPTION
**Pull request by Takane42**
Added Review on Indoensian Translation in Python

This pull request (PR) is made in reference to:
#157

### CODE REVIEW

**Comment by Takane42** [comment]
Uh... help? @madiedgar

**Review by madiedgar — APPROVED** [review]
This looks great @Takane42! 👍

**Comment by madiedgar** [comment]
> Uh... help? @madiedgar

Are you concerned about the tests failing? It's a bug that's fixed in the master branch, so no need to worry!

**Comment by madiedgar** [comment]
Thank you again for your contribution! Really appreciate you 👏

**Comment by Takane42** [comment]
im sorry for the late reply but... sure no problem. Thanks for merge'ing my review @madiedgar

**Pull request merged**
