### PR TITLE
#43 reviewed translations

### PR DESCRIPTION
**Pull request by twille00**
I reviewed the python-translations

✓ - good translation
? - not good translation

### CODE REVIEW

**Comment by twille00** [comment]
Ascii-Symbols may lead to errors... can you give an alternate to me or replace ✓ with any symbol you like.

**Comment by madiedgar** [comment]
Thank you so much @twille00 for your translation reviews!! This is great 👏 Could you help me a bit as there are a couple of people that translated German at the same time? (great problem to have!)

- [ ] Update the `german-translation` with the `master` branch
- [ ] Use the review conventions described in #43 as you integrate your changes in the updated `de.yml` file
- [ ] Move the `de.yml` file inside the `locale/` folder

**Comment by madiedgar** [comment]
Hey @twille00, let me know if you need any help with updating this! 👍 thanks so much for your work thus far!

**Comment by madiedgar** [comment]
Thank you so much @twille00 for your contribution! I added your review in [this commit](https://github.com/legesher/legesher-translations/commit/2d2710907633b1472855abe59a0961cd67c573c4) and added you as a co-author 👍 Thank you again!

**Pull request closed without merging**
