### PR TITLE
add CONTRIBUTING file

### LINKED ISSUE #75: Add CONTRIBUTING.md file
Add a `CONTRIBUTING.md` file in the root of the repository that contains this content:

```md
See the [Legesher contributing guide](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md)
```

Simple enough 👍 Please ask to be assigned to this issue so we don't have duplicates 😄

### PR DESCRIPTION
**Pull request by locemarn**
Fix #75

### CODE REVIEW

**Comment by locemarn** [comment]
Sorry, but how can i do it??

**Comment by madiedgar** [comment]
Hey @locemarn 👋 You can make a new commit changing the contents of the `CONTRIBUTING.md` file to this line:

`See the [Legesher contributing guide](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md)`

**Comment by madiedgar** [comment]
Hey @locemarn any updates on this? Happy to help!

**Comment by madiedgar** [comment]
Closing as this was resolved in #107

**Pull request closed without merging**
