### PR TITLE
Add/Modify Hindi Translation

### PR DESCRIPTION
**Pull request by bhaveshgoyal182**
## Title
Add/Review/Modify Hindi Translation

This pull request (PR) is made in reference to:  #121 

## Description
1.Reviewed ATOM ,AFL,BASH,C,C++
2.Added AGDA and few C++ translations in Hindi

### CODE REVIEW

**Comment by bhaveshgoyal182** [comment]
@madiedgar please check this once if it meets your requirements.

**Review by madiedgar — APPROVED** [review]
Looks incredible @bhaveshgoyal182 👍 Thank you for your contribution!

**Comment by madiedgar** [comment]
Thank you @bhaveshgoyal182 for your quality contribution! Its been a pleasure working with you 👍

**Comment by bhaveshgoyal182** [comment]
Welcome @madiedgar ,
Ya sure would love to do that as well 👍🏻

**Pull request merged**
